### ISSUE TITLE
 [Bug] Dark reader permanently disabled on new domain. 

### ISSUE THREAD

**Issue by Th3FatKat** [11Tuvork28/invidious#16] opened 2023-02-15 20:04 UTC
[Dark reader's](https://darkreader.org/) dark mode doesn't work on the new domain.
[watch.thekitty.zone](https://watch.thekitty.zone/):
![SS_full-230215-2103-31](https://user-images.githubusercontent.com/100007938/219140490-5d1d648d-80ad-4c88-b9f2-e00167c86397.png)
[invidio.xamh.de](invidio.xamh.de):
![invidio xamh de](https://user-images.githubusercontent.com/100007938/219140039-3efe4602-6db4-460e-80cd-90847d944b43.png)

**Comment by AndromedaCLI** [comment] 2023-02-15 20:12
Oh hmm that is fascinating, does it work on other instances? Only possible reason I can think of the top of my head is that in some update something broke, as the old domain is running an outdated version...
I will do some tests tomorrow, as that is frustrating for users. Thanks for bringing this up! Much appreciated.

**Comment by Th3FatKat** [comment] 2023-02-15 22:05
It works as expected on all of the public instances [listed](https://docs.invidious.io/instances/). It's been present for a couple of weeks now. I'm surprised it wasn't in another issue, seeing as it's been a few weeks and given the addon's popularity.

**Comment by AndromedaCLI** [comment] 2023-02-16 13:35
So I tested it just now on FF and Chromium, it works as it should for me!
What browser do you use? and which version? Also which os?
I'm just trying to reproduce it!

**Comment by Th3FatKat** [comment] 2023-02-17 17:09
Currently on Librewolf V109.0.1 On Arch Linux. 
Don't know why it would be different, as I said, works fine on every other instance.

**Comment by AndromedaCLI** [comment] 2023-02-18 20:03
> Librewolf V109.0.1 On Arch Linux.

Thats my exact setup as well, works fine. Did you disable any other extension to test it?

**Comment by Th3FatKat** [comment] 2023-02-19 18:25
Disabled them all, leaving only DarkReader, with no change. Then I tried in a private tab, same procedure, same blinding result. What do you think? It did work normally when the change was first announced on the invidio.xamh.de domain, stopping about a week after.

**Comment by AndromedaCLI** [comment] 2023-02-19 18:36
Okay weird, so the only thing that changed was in this [commit](https://github.com/TheKitty-zone/invidious/commit/d267d5bc6c5bd30cd57a7953fc27949056cbed3a) but this is also live on the old domain. I don't get it and can't reproduce it, this is frustrating I'm that you're experiencing this. I'm going to investigated some more things but I'm running out of ideas honestly.
Have you tried different browsers? I assume so but just want to confirm.

**Comment by Th3FatKat** [comment] 2023-02-20 15:54
Yes, I've tried Chromium and Firefox as well, where the extension works normally. Something I did notice is that DR appears differently from the default installation on them, i.e. some dev mode to change the default themes' colors, similarly to the [Stylus](https://add0n.com/stylus.html) extension. No form of special alteration appears to the new domain in this dev mode. It behaves the same as with protected sites. Reinstalling doesn't change behavior. See below Chromium - Librewolf(the disabled button registers when pressed, but does nothing):
![DR_Chromium](https://user-images.githubusercontent.com/100007938/220148736-33e86d01-c609-4cbd-9970-550cd096202e.png) ![DR_Librewolf](https://user-images.githubusercontent.com/100007938/220151895-fa89b1a8-df3c-427d-9c9d-584f967ddbac.png)

The reason I chose to submit the issue here is because the new domain is the only instance on which this happens. If the issue is non-replicable, feel free to close the thread.

**Comment by Ashirg-ch** [comment] 2023-02-23 11:40
Tested on Windows 10, Firefox 110.0. Could not replicate, it works fine for me.

**Comment by AndromedaCLI** [comment] 2023-02-23 11:59
Closing it now due to it being not reproducible and or possible configuration error

**Closed as completed by AndromedaCLI** 2023-02-23 11:59 UTC
Labels: bug

**Comment by Th3FatKat** [comment] 2023-03-20 03:16
UPDATE: Disabling Dark Reader is a cascading action. So when disabling on a domain, all sub-domains are also affected. Not only that; the only way to restore darkreader is to re-enable on the top domain, as you'll be blocked from doing so at the sub-domain level. 
After disabling on thekitty.zone, this issue arose and I did not correlate the two actions. Sorry for wasting your time.
